### PR TITLE
CORE-314 Export export_secret_key (sic)

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by planck-jk** [comment]
Looks fine, thanks. I can't see a "grant review" button.

**Comment by ghost** [comment]
> Looks fine, thanks. I can't see a "grant review" button.

If you are on the "Files changed" tab (https://github.com/plancksecurity/foundation-planckJSONServerWrapper/pull/2/files), then there is a green "Review changes" button that leads to some actions.

**Review by planck-jk — APPROVED** [review]
Looks fine. I assume you've compiled it ;-)

**Comment by ghost** [comment]
> Looks fine. I assume you've compiled it ;-)

It even works, I tested it with a generic JSON client.

**Review by ip-plank-security — APPROVED** [review]

**Comment by planck-jk** [comment]
Needless to say that we need to get a release with the change integrated 😉.

**Pull request merged**
